
// authorize an user
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const INITIALIZE_STORAGE = 'INITIALIZE_STORAGE';

// register user
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE';

// reset user password
export const USER_RESET_PASSWORD_REQUEST = 'USER_RESET_PASSWORD_REQUEST';
export const USER_RESET_PASSWORD_SUCCESS = 'USER_RESET_PASSWORD_SUCCESS';
export const USER_RESET_PASSWORD_FAILURE = 'USER_RESET_PASSWORD_FAILURE';

// update user password
export const USER_UPDATE_PASSWORD_REQUEST = 'USER_UPDATE_PASSWORD_REQUEST';
export const USER_UPDATE_PASSWORD_SUCCESS = 'USER_UPDATE_PASSWORD_SUCCESS';
export const USER_UPDATE_PASSWORD_FAILURE = 'USER_UPDATE_PASSWORD_FAILURE';

// get list pet
export const GET_LIST_PET_REQUEST = 'GET_LIST_PET_REQUEST';
export const GET_LIST_PET_SUCCESS = 'GET_LIST_PET_SUCCESS';
export const GET_LIST_PET_FAILURE = 'GET_LIST_PET_FAILURE';

// delete pet
export const DELETE_PET_REQUEST = 'DELETE_PET_REQUEST';
export const DELETE_PET_SUCCESS = 'DELETE_PET_SUCCESS';
export const DELETE_PET_FAILURE = 'DELETE_PET_FAILURE';

// get pet detail
export const GET_PET_DETAIL_REQUEST = 'GET_PET_DETAIL_REQUEST';
export const GET_PET_DETAIL_SUCCESS = 'GET_PET_DETAIL_SUCCESS';
export const GET_PET_DETAIL_FAILURE = 'GET_PET_DETAIL_FAILURE';

// add new pet
export const ADD_PET_REQUEST = 'ADD_PET_REQUEST';
export const ADD_PET_SUCCESS = 'ADD_PET_SUCCESS';
export const ADD_PET_FAILURE = 'ADD_PET_FAILURE';

// add new pet
export const EDIT_PET_REQUEST = 'EDIT_PET_REQUEST';
export const EDIT_PET_SUCCESS = 'EDIT_PET_SUCCESS';
export const EDIT_PET_FAILURE = 'EDIT_PET_FAILURE';

// upload image pet
export const UPLOAD_IMAGE_PET_REQUEST = 'UPLOAD_IMAGE_PET_REQUEST';
export const UPLOAD_IMAGE_PET_SUCCESS = 'UPLOAD_IMAGE_PET_SUCCESS';
export const UPLOAD_IMAGE_PET_FAILURE = 'UPLOAD_IMAGE_PET_FAILURE';

// delete image pet
export const DELETE_IMAGE_UPLOAD_REQUEST = 'DELETE_IMAGE_UPLOAD_REQUEST';
export const DELETE_IMAGE_UPLOAD_SUCCESS = 'DELETE_IMAGE_UPLOAD_SUCCESS';
export const DELETE_IMAGE_UPLOAD_FAILURE = 'DELETE_IMAGE_UPLOAD_FAILURE';

// delete image pet
export const DELETE_IMAGE_PET_REQUEST = 'DELETE_IMAGE_PET_REQUEST';
export const DELETE_IMAGE_PET_SUCCESS = 'DELETE_IMAGE_PET_SUCCESS';
export const DELETE_IMAGE_PET_FAILURE = 'DELETE_IMAGE_PET_FAILURE';

// clear error code
export const  CLEAR_ERROR_CODE = 'CLEAR_ERROR_CODE';
export const CLEAR_ERROR_CODE_LOGIN = 'CLEAR_ERROR_CODE_LOGIN';

// get profile user information
export const GET_PROFILE_USER_REQUEST = 'GET_PROFILE_USER_REQUEST';
export const GET_PROFILE_USER_SUCCESS = 'GET_PROFILE_USER_SUCCESS';
export const GET_PROFILE_USER_FAILURE = 'GET_PROFILE_USER_FAILURE';

// edit profile use
export const EDIT_PROFILE_USER_REQUEST = 'EDIT_PROFILE_USER_REQUEST';
export const EDIT_PROFILE_USER_SUCCESS = 'EDIT_PROFILE_USER_SUCCESS';
export const EDIT_PROFILE_USER_FAILURE = 'EDIT_PROFILE_USER_FAILURE';

// edit profile use
export const UPLOAD_AVATAR_USER_REQUEST = 'UPLOAD_AVATAR_USER_REQUEST';
export const UPLOAD_AVATAR_USER_SUCCESS = 'UPLOAD_AVATAR_USER_SUCCESS';
export const UPLOAD_AVATAR_USER_FAILURE = 'UPLOAD_AVATARE_USER_FAILURE';

// change password use
export const CHANGE_PASSWORD_USER_REQUEST = 'CHANGE_PASSWORD_USER_REQUEST';
export const CHANGE_PASSWORD_USER_SUCCESS = 'CHANGE_PASSWORD_USER_SUCCESS';
export const CHANGE_PASSWORD_USER_FAILURE = 'CHANGE_PASSWORD_USER_FAILURE';

// logout user
export const LOGOUT_USER = 'LOGOUT_USER';

// get order list history
export const GET_ORDER_HISTORY_REQUEST = 'GET_ORDER_HISTORY_REQUEST';
export const GET_ORDER_HISTORY_SUCCESS = 'GET_ORDER_HISTORY_SUCCESS';
export const GET_ORDER_HISTORY_FAILURE = 'GET_ORDER_HISTORY_FAILURE';

// get service list history
export const GET_SERVICE_HISTORY_REQUEST = 'GET_SERVICE_HISTORY_REQUEST';
export const GET_SERVICE_HISTORY_SUCCESS = 'GET_SERVICE_HISTORY_SUCCESS';
export const GET_SERVICE_HISTORY_FAILURE = 'GET_SERVICE_HISTORY_FAILURE';

// food get list coffee
export const GET_LIST_FOOD_REQUEST = 'GET_LIST_FOOD_REQUEST';
export const GET_LIST_FOOD_SUCCESS = 'GET_LIST_FOOD_SUCCESS';
export const GET_LIST_FOOD_FAILURE = 'GET_LIST_FOOD_FAILURE';

// food get list coffee
export const ORDER_FOOD_REQUEST = 'ORDER_FOOD_REQUEST';
export const ORDER_FOOD_SUCCESS = 'ORDER_FOOD_SUCCESS';
export const ORDER_FOOD_FAILURE = 'ORDER_FOOD_FAILURE';

// food get list coffee
export const GET_LIST_SERVICE_REQUEST = 'GET_LIST_SERVICE_REQUEST';
export const GET_LIST_SERVICE_SUCCESS = 'GET_LIST_SERVICE_SUCCESS';
export const GET_LIST_SERVICE_FAILURE = 'GET_LIST_SERVICE_FAILURE';

// food get list coffee
export const ORDER_SERVICE_REQUEST = 'ORDER_SERVICE_REQUEST';
export const ORDER_SERVICE_SUCCESS = 'ORDER_SERVICE_SUCCESS';
export const ORDER_SERVICE_FAILURE = 'ORDER_SERVICE_FAILURE';

// order food
export const ORDER_FOOD_ITEM_SUCCESS = 'ORDER_FOOD_ITEM_SUCCESS';

// order remove item bill
export const ORDER_REMOVE_ITEM_BILL = 'ORDER_REMOVE_ITEM_BILL';

// comfirm order
export const ORDER_COMFIRM_REQUEST = 'ORDER_COMFIRM_REQUEST';
export const ORDER_COMFIRM_SUCCESS = 'ORDER_COMFIRM_SUCCESS';
export const ORDER_COMFIRM_FAILURE = 'ORDER_COMFIRM_FAILURE';

// get list service category
export const SERVICE_GET_LIST_CATEGORY_REQUEST = 'SERVICE_GET_LIST_CATEGORY_REQUEST';
export const SERVICE_GET_LIST_CATEGORY_SUCCESS = 'SERVICE_GET_LIST_CATEGORY_SUCCESS';
export const SERVICE_GET_LIST_CATEGORY_FAILURE = 'SERVICE_GET_LIST_CATEGORY_FAILURE';

// get service by category
export const GET_SERVICES_BY_CATEGORY_REQUEST = 'GET_SERVICES_BY_CATEGORY_REQUEST';
export const GET_SERVICES_BY_CATEGORY_SUCCESS = 'GET_SERVICES_BY_CATEGORY_SUCCESS';
export const GET_SERVICES_BY_CATEGORY_FAILURE = 'GET_SERVICES_BY_CATEGORY_FAILURE';

// select services
export const SERVICES_SELECTED_SUCCESS = 'SERVICES_SELECTED_SUCCESS';

// remove item service in bill
export const SERVICES_REMOVE_ITEM_BILL = 'SERVICES_REMOVE_ITEM_BILL';

// clear service
export const SERVICES_CELAR = 'SERVICES_CELAR';

// comfirm order
export const SERVICES_COMFIRM_REQUEST = 'SERVICES_COMFIRM_REQUEST';
export const SERVICES_COMFIRM_SUCCESS = 'SERVICES_COMFIRM_SUCCESS';
export const SERVICES_COMFIRM_FAILURE = 'SERVICES_COMFIRM_FAILURE';
